appid: zrunframrwork
spring:
  application:
    name: zrunframrwork
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test
server:
  port: 9000
  #是否开启全局异常捕捉
  exception:
    capture: true


test: 78979

ab:
  cd:
    ef:
      gh:
        nr: 9


netty:
  option: 1024



pt:
  datasource:
    url: jdbc:mysql://192.168.156.190:3306/canlian?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClass: com.mysql.cj.jdbc.Driver


redis:
    host: localhost
    port: 6379


array:
  zz: ["1","2","3"]



